import type { Metadata } from 'next';
import localFont from 'next/font/local';
import ReactQueryProvider from '@/components/react-query-provider';
import DefaultNavBar from '@/components/navBar/navBar';
import MobileNavBar from '@/components/navBar/mobileNavBar';
import Posting from '@/components/post/posting';
import './globals.css';

const geistSans = localFont({
  src: '../fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});
const geistMono = localFont({
  src: '../fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <ReactQueryProvider>
          <div className="flex w-full min-h-[calc(100dvh-64px)] h-[calc(100dvh-64px)] max-h-[calc(100dvh-64px)] lg:min-h-screen lg:h-screen lg:max-h-screen">
            <DefaultNavBar />
            {children}
            <MobileNavBar />
            <Posting />
          </div>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
